# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_management.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16order_management.proto\x12\x0fordermanagement\"=\n\x0cOrderRequest\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"O\n\x12OrderUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04item\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"\x15\n\x07OrderId\x12\n\n\x02id\x18\x01 \x01(\t\"J\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04item\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc3\x02\n\x0fOrderManagement\x12L\n\x0b\x43reateOrder\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse\x12\x44\n\x08GetOrder\x12\x18.ordermanagement.OrderId\x1a\x1e.ordermanagement.OrderResponse\x12R\n\x0bUpdateOrder\x12#.ordermanagement.OrderUpdateRequest\x1a\x1e.ordermanagement.OrderResponse\x12H\n\x0b\x44\x65leteOrder\x12\x18.ordermanagement.OrderId\x1a\x1f.ordermanagement.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=43
  _globals['_ORDERREQUEST']._serialized_end=104
  _globals['_ORDERUPDATEREQUEST']._serialized_start=106
  _globals['_ORDERUPDATEREQUEST']._serialized_end=185
  _globals['_ORDERID']._serialized_start=187
  _globals['_ORDERID']._serialized_end=208
  _globals['_ORDERRESPONSE']._serialized_start=210
  _globals['_ORDERRESPONSE']._serialized_end=284
  _globals['_DELETERESPONSE']._serialized_start=286
  _globals['_DELETERESPONSE']._serialized_end=319
  _globals['_ORDERMANAGEMENT']._serialized_start=322
  _globals['_ORDERMANAGEMENT']._serialized_end=645
# @@protoc_insertion_point(module_scope)
