global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'logging_service'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Assuming your logging service is running on localhost:8000


#docker run -p 9090:9090 -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus