apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: account-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongo-account:27011/account-management
          image: xiru2024/account:latest
          name: account
          imagePullPolicy: Always
          ports:
            - containerPort: 11500
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      restartPolicy: Always
