apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongo-orders
  name: mongo-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-orders
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mongo-orders
    spec:
      containers:
        - image: mongo
          name: mongo-orders
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-orders-data
      restartPolicy: Always
      volumes:
        - name: mongo-orders-data
          persistentVolumeClaim:
            claimName: mongo-orders-data
