apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: order-management-service
  name: order-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-management-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: order-management-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongo-orders:27017/order-management
          image: xiru2024/order-management:latest
          name: order-management
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
