apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: product-inventory-service
  name: product-inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-inventory-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: product-inventory-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:29092
            - name: MONGO_URI
              value: mongodb://mongo-inventory:27014/product-inventory
          image: xiru2024/product-inventory:latest
          name: product-inventory
      restartPolicy: Always
