apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
#          livenessProbe:
#            exec:
#              command:
#                - echo srvr | nc localhost 2181 || exit 1
#            failureThreshold: 3
#            periodSeconds: 10
#            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "echo ruok | nc localhost 2181"
            initialDelaySeconds: 20  # Allow more startup time
            periodSeconds: 10         # Check less frequently
            timeoutSeconds: 5         # Increase timeout
            failureThreshold: 5       # Allow more failures before restart


          name: zookeeper
          ports:
            - containerPort: 2181
              protocol: TCP
      restartPolicy: Always
