# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"P\n\nLogRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"\x19\n\x0bLogResponse\x12\n\n\x02id\x18\x01 \x01(\t\"V\n\x0eGetLogsRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x01\"2\n\x0fGetLogsResponse\x12\x1f\n\x04logs\x18\x01 \x03(\x0b\x32\x11.logging.LogEntry\"Z\n\x08LogEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x32\x88\x01\n\x0eLoggingService\x12\x36\n\x07SendLog\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\"\x00\x12>\n\x07GetLogs\x12\x17.logging.GetLogsRequest\x1a\x18.logging.GetLogsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=106
  _globals['_LOGRESPONSE']._serialized_start=108
  _globals['_LOGRESPONSE']._serialized_end=133
  _globals['_GETLOGSREQUEST']._serialized_start=135
  _globals['_GETLOGSREQUEST']._serialized_end=221
  _globals['_GETLOGSRESPONSE']._serialized_start=223
  _globals['_GETLOGSRESPONSE']._serialized_end=273
  _globals['_LOGENTRY']._serialized_start=275
  _globals['_LOGENTRY']._serialized_end=365
  _globals['_LOGGINGSERVICE']._serialized_start=368
  _globals['_LOGGINGSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
