# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/product_catalog.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/grpc/product_catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pp/grpc/product_catalog.proto\x12\x0eproductcatalog\"`\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"a\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"\x17\n\tProductID\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x0fOperationStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcf\x02\n\x15ProductCatalogService\x12M\n\nAddProduct\x12\x1e.productcatalog.ProductRequest\x1a\x1f.productcatalog.ProductResponse\x12H\n\nGetProduct\x12\x19.productcatalog.ProductID\x1a\x1f.productcatalog.ProductResponse\x12P\n\rUpdateProduct\x12\x1e.productcatalog.ProductRequest\x1a\x1f.productcatalog.ProductResponse\x12K\n\rDeleteProduct\x12\x19.productcatalog.ProductID\x1a\x1f.productcatalog.OperationStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.product_catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=50
  _globals['_PRODUCTREQUEST']._serialized_end=146
  _globals['_PRODUCTRESPONSE']._serialized_start=148
  _globals['_PRODUCTRESPONSE']._serialized_end=245
  _globals['_PRODUCTID']._serialized_start=247
  _globals['_PRODUCTID']._serialized_end=270
  _globals['_OPERATIONSTATUS']._serialized_start=272
  _globals['_OPERATIONSTATUS']._serialized_end=322
  _globals['_PRODUCTCATALOGSERVICE']._serialized_start=325
  _globals['_PRODUCTCATALOGSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
