# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_service import product_catalog_pb2 as app_dot_grpc_dot_product__catalog__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/grpc/product_catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductCatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProduct = channel.unary_unary(
                '/productcatalog.ProductCatalogService/AddProduct',
                request_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/productcatalog.ProductCatalogService/GetProduct',
                request_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductID.SerializeToString,
                response_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/productcatalog.ProductCatalogService/UpdateProduct',
                request_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/productcatalog.ProductCatalogService/DeleteProduct',
                request_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductID.SerializeToString,
                response_deserializer=app_dot_grpc_dot_product__catalog__pb2.OperationStatus.FromString,
                _registered_method=True)


class ProductCatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProduct,
                    request_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductRequest.FromString,
                    response_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductID.FromString,
                    response_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductRequest.FromString,
                    response_serializer=app_dot_grpc_dot_product__catalog__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=app_dot_grpc_dot_product__catalog__pb2.ProductID.FromString,
                    response_serializer=app_dot_grpc_dot_product__catalog__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productcatalog.ProductCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productcatalog.ProductCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductCatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productcatalog.ProductCatalogService/AddProduct',
            app_dot_grpc_dot_product__catalog__pb2.ProductRequest.SerializeToString,
            app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productcatalog.ProductCatalogService/GetProduct',
            app_dot_grpc_dot_product__catalog__pb2.ProductID.SerializeToString,
            app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productcatalog.ProductCatalogService/UpdateProduct',
            app_dot_grpc_dot_product__catalog__pb2.ProductRequest.SerializeToString,
            app_dot_grpc_dot_product__catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productcatalog.ProductCatalogService/DeleteProduct',
            app_dot_grpc_dot_product__catalog__pb2.ProductID.SerializeToString,
            app_dot_grpc_dot_product__catalog__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
