# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'account_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x63\x63ount_service.proto\x12\x11\x61\x63\x63ountmanagement\"?\n\x0e\x41\x63\x63ountRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"Q\n\x14\x41\x63\x63ountUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x17\n\tAccountId\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x0f\x41\x63\x63ountResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x02\n\x0e\x41\x63\x63ountService\x12V\n\rCreateAccount\x12!.accountmanagement.AccountRequest\x1a\".accountmanagement.AccountResponse\x12N\n\nGetAccount\x12\x1c.accountmanagement.AccountId\x1a\".accountmanagement.AccountResponse\x12\\\n\rUpdateAccount\x12\'.accountmanagement.AccountUpdateRequest\x1a\".accountmanagement.AccountResponse\x12P\n\rDeleteAccount\x12\x1c.accountmanagement.AccountId\x1a!.accountmanagement.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=44
  _globals['_ACCOUNTREQUEST']._serialized_end=107
  _globals['_ACCOUNTUPDATEREQUEST']._serialized_start=109
  _globals['_ACCOUNTUPDATEREQUEST']._serialized_end=190
  _globals['_ACCOUNTID']._serialized_start=192
  _globals['_ACCOUNTID']._serialized_end=215
  _globals['_ACCOUNTRESPONSE']._serialized_start=217
  _globals['_ACCOUNTRESPONSE']._serialized_end=275
  _globals['_DELETERESPONSE']._serialized_start=277
  _globals['_DELETERESPONSE']._serialized_end=310
  _globals['_ACCOUNTSERVICE']._serialized_start=313
  _globals['_ACCOUNTSERVICE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
